package com.ba.controllers;

import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDate;

import com.ba.dao.connectDB;
import com.mysql.cj.xdevapi.Statement;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet("/addNewLoan")
public class addNewLoan extends HttpServlet {
	@Override
	protected void doPost(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		String loanDate = req.getParameter("loanDate");
		/*
		 * LocalDate loanDate= LocalDate.parse(Date);
		 */
		String loanName = req.getParameter("name");
		Long loanContactNo = Long.parseLong(req.getParameter("number"));
		String loanGender = req.getParameter("gender");
		String loanAddress = req.getParameter("address");
		Double loanAmt = Double.parseDouble(req.getParameter("grandAmt"));
		Double loanInterest = Double.parseDouble(req.getParameter("interest"));
		Double monthlyInterest = (loanAmt * loanInterest) / 100.0;

		try {
			Connection conn = connectDB.getConnection();
			String customerSQL = "INSERT INTO loan_customers (loan_date, customer_name, phone_no, gender, address, loan_amount, interest_percent, monthly_interest) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?)";

			// this return generated key is actually used to get the auto generated loan_no
			// from the database so that
			// it can be used to store the loan_item
			PreparedStatement ps = conn.prepareStatement(customerSQL, PreparedStatement.RETURN_GENERATED_KEYS);
			ps.setString(1, loanDate);
			ps.setString(2, loanName);
			ps.setLong(3, loanContactNo);
			ps.setString(4, loanGender);
			ps.setString(5, loanAddress);
			ps.setDouble(6, loanAmt);
			ps.setDouble(7, loanInterest);
			ps.setDouble(8, monthlyInterest);
			ps.executeUpdate();
			ResultSet generatedKeys = ps.getGeneratedKeys();
			int loanNo = 0;
			if (generatedKeys.next()) {
				loanNo = generatedKeys.getInt(1); // this takes the autogenerated loanNo. present in the loan customer
													// database
				// and use this loanNo to be inserted in the items database
			}

			// this values in double quotation are only names passed in in the input section
			String[] itemNames = req.getParameterValues("itemName[]");
			String[] descriptions = req.getParameterValues("description[]");
			String[] weights = req.getParameterValues("weight[]");
			String[] quantities = req.getParameterValues("quantity[]");
			String[] prices = req.getParameterValues("price[]");

			String itemSQL = "INSERT INTO loan_items (loan_no,item_name, description, weight, quantity, price) VALUES (?, ?, ?, ?, ?, ?)";
			PreparedStatement ps1 = conn.prepareStatement(itemSQL);

			for (int i = 0; i < itemNames.length; i++) {
				ps1.setInt(1, loanNo);
				ps1.setString(2, itemNames[i]);
				ps1.setString(3, descriptions[i]);
				ps1.setDouble(4, Double.parseDouble(weights[i]));
				ps1.setInt(5, Integer.parseInt(quantities[i]));
				ps1.setDouble(6, Double.parseDouble(prices[i]));
				ps1.addBatch();
			}
			ps1.executeBatch();

			conn.close();
			resp.sendRedirect("loanProvided.jsp");
		} catch (Exception e) {
			e.printStackTrace();
			resp.getWriter().write("Error saving loan. Please try again.");
		}
	}
}
